export const authActionType = {
    LOGIN_SUCCESS : "LOGIN_SUCCESS",
    LOGIN_ERR : "LOGIN_Err",
    SIGNOUT_SUCCESS:"SIGNOUT_SUCCESS",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_ERR: "SIGNUP_ERR"
}